const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_ALL_QUESTIONS: "STORE_ALL_QUESTIONS",
   // STORE_NEW_QUESTION: "STORE_NEW_QUESTION",
   // STORE_NEW_ANSWER: "STORE_NEW_ANSWER",
};

export default actions;
